//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestAPI.rc
//
#define ID_BUTTON_GET                   3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTAPI_DIALOG              102
#define IDD_DIALOG_API                  102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_RELAY                135
#define IDD_DIALOG_DEBUG                138
#define IDD_DIALOG_COMM                 139
#define IDD_DIALOG_TAG                  140
#define IDD_DIALOG_READER               141
#define IDD_DIALOG_SFGEN                142
#define IDD_DIALOG_STDFGEN              143
#define IDC_BUTTON_RF_OPEN              1000
#define IDC_BUTTON_RF_CLOSE             1001
#define IDC_BUTTON_RF_REG_READER        1002
#define IDC_BUTTON_RF_REG_TAG           1003
#define IDC_BUTTON_GET_READER_VERSION   1003
#define IDC_BUTTON_RESET_READER         1004
#define IDC_BUTTON_CONFIG_READER        1005
#define IDC_STATIC_SEND                 1006
#define IDC_BUTTON_RF_REG_DEBUG_EVENT   1006
#define IDC_BUTTON_RF_OPEN_SOCKET       1007
#define IDC_STATIC_TEXT_SEND            1008
#define IDC_EDIT_COM_PORT               1009
#define IDC_LIST                        1010
#define IDC_BUTTON_CLEAR_LIST           1011
#define IDC_COMB_TAG_TYPE               1012
#define IDC_EDITHOST_ID                 1013
#define IDC_EDIT_HOST_ID                1013
#define IDC_EDIT_TAG_ID                 1014
#define IDC_EDIT_TAG_ID_3               1014
#define IDC_EDIT_PERIODIC_REPORT_TIME   1014
#define IDC_EDIT_READER_ID              1015
#define IDC_EDIT_LOW_LIMIT_TEMP         1015
#define IDC_RADIO_115200                1016
#define IDC_EDIT_UP_LIMIT_TEMP          1016
#define IDC_RADIO_57600                 1017
#define IDC_BUTTON_CALL_TAG             1018
#define IDC_EDIT_FGEN_ID                1019
#define IDC_EDIT_REPEATER_ID            1020
#define IDC_EDIT_TAG_ID_2               1021
#define IDC_EDIT_TAG_ID_1               1022
#define IDC_COMB_SELECT_TYPE            1023
#define IDC_EDIT_NEW_READER_ID          1024
#define IDC_COMB_SELECT_TYPE2           1024
#define IDC_COMB_ID_RANGE               1024
#define IDC_EDIT_NEW_HOST_ID            1025
#define IDC_COMBO_NEW_READER_FUNC_TYPE  1026
#define IDC_EDIT_NEW_REPEATER_ID        1027
#define IDC_EDIT_READER_TX_TIME         1027
#define IDC_COMB_READER_FUNC_TYPE       1028
#define IDC_EDIT_PORT_NUM               1029
#define IDC_BUTTON_QUERY_TAG            1029
#define IDC_RADIO_RS232                 1030
#define IDC_RADIO_NETWORK               1031
#define IDC_BUTTON_RF_CLOSE_SOCKET      1032
#define IDC_EDIT_IP_ADDR                1033
#define IDC_BUTTON_RF_CLOSE_SOCKET2     1033
#define IDC_BUTTON_RF_SCAN_IP           1033
#define IDC_STATIC_HN                   1034
#define IDC_BUTTON_RF_SCAN_IP2          1034
#define IDC_BUTTON_RF_RESET_READER_SOCKET 1034
#define IDC_STATIC_IP_ADDR              1035
#define IDC_STATIC_PN                   1036
#define IDC_STATIC_IP_ADDR2             1036
#define IDC_STATIC_COM_PORT             1037
#define IDC_STATIC_COM_STATUS           1038
#define IDC_BUTTON_DISABLE_READER       1039
#define IDC_BUTTON_ENABLE_READER        1040
#define IDC_BUTTON_GET_API_VERSION      1041
#define IDC_BUTTON_READ_TAG             1041
#define IDC_BUTTON_ENABLE_TAG           1042
#define IDC_BUTTON_CALL_TAG3            1043
#define IDC_BUTTON_DISABLE_TAG          1043
#define IDC_BUTTON_SCAN_NETWORK         1044
#define IDC_BUTTON_DEFINE_TAG_READER    1044
#define IDC_LIST_IP                     1045
#define IDC_BUTTON_CLEAR                1046
#define IDC_RADIO_RADIO_SPECIFIC_IP     1047
#define IDC_RADIO_ALL_IPS               1048
#define IDC_LIST_RECV                   1051
#define IDC_EDIT_READER_WT_TIME         1051
#define IDC_LIST_SEND                   1052
#define IDC_COMBO_RDR_TYPE              1052
#define IDC_BUTTON_CLEAR_RECV           1053
#define IDC_BUTTON_CLEAR_SEND           1054
#define IDC_BUTTON_SCAN_NETWORK2        1055
#define IDC_BUTTON_WRITE_TAG            1056
#define IDC_EDIT_MEM_START_ADDR         1057
#define IDC_EDIT_MEM_DATA_LEN           1058
#define IDC_EDIT3                       1059
#define IDC_EDIT_MEM_DATA               1059
#define IDC_BUTTON_GET_TEMP_CONFIG      1060
#define IDC_EDIT4                       1060
#define IDC_RADIO_Long_INTERVAL         1061
#define IDC_EDIT5                       1061
#define IDC_RADIO_SHORT_INTERVAL        1062
#define IDC_BUTTON_SET_TEMP_CONFIG      1063
#define IDC_EDIT_MEM_DATA2              1064
#define IDC_BUTTON_SET_TEMP_LOG_TIMESTAMP 1064
#define IDC_BUTTON_ENABLE_RELAY         1065
#define IDC_BUTTON_GET_TEMP_LOG_TIMESTAMP2 1065
#define IDC_BUTTON_ENABLE_RELAY2        1066
#define IDC_BUTTON_GET_INPUT            1066
#define IDC_BUTTON_GET_TEMP             1067
#define IDC_BUTTON_GET_TAG_TEMP         1067
#define IDC_EDIT_SCAN_IP                1068
#define IDC_BUTTON_GET_TAG_TEMP_CALIB   1069
#define IDC_EDIT_COMM_HOST_ID           1069
#define IDC_CHECK_REPORT_UNDER          1070
#define DC_BUTTON_SET_TAG_TEMP_CALIB    1070
#define IDC_BUTTON_SET_TAG_TEMP_CALIB   1070
#define IDC_EDIT_TAG_TEMP_CALIB         1071
#define IDC_CHECK_REPORT_UPPER          1072
#define IDC_BUTTON_GET_INPUT2           1072
#define IDC_BUTTON_SET_RDR_FS           1072
#define IDC_CHECK_REPORT_TEMP_UNDER     1072
#define IDC_CHECK_REPORT_PERIODIC       1073
#define IDC_BUTTON_SET_RDR_FS2          1073
#define IDC_BUTTON_GET_RDR_FS           1073
#define IDC_CHECK_REPORT_TEMP_UPPER     1073
#define IDC_COMBO_NUM_READ              1074
#define IDC_BUTTON_RESET_SFGEN          1074
#define IDC_CHECK_REPORT_TEMP_PERIODIC  1074
#define IDC_BUTTON_QUERY_SFGEN          1075
#define IDC_COMBO_NUM_READ_AVE          1075
#define IDC_RADIO_TIME_HOUR             1076
#define IDC_BUTTON_CALL_TAG_SFGEN       1076
#define IDC_RADIO_TIME_MINUTE           1077
#define IDC_BUTTON_SET_FS_SFGEN         1077
#define IDC_RADIO_RELAY1                1078
#define IDC_EDIT_ABS_FS_SFGEN           1078
#define IDC_RADIO_RELAY2                1079
#define IDC_BUTTON_GET_FS_SFGEN         1079
#define IDC_BUTTON_SET_FS_SFGEN2        1079
#define IDC_RADIO_IGNOR_INPUT1          1080
#define IDC_BUTTON_SET_CONFIG_SFGEN     1080
#define IDC_RADIO_REPORT_INPUT1         1081
#define IDC_RADIO_RDR_WT_SEC            1081
#define IDC_RADIO_ENABLE                1082
#define IDC_RADIO_NO_CHANGE_INPUT1      1082
#define IDC_RADIO_RDR_WT_MIN            1082
#define IDC_RADIO_DISABLE               1083
#define IDC_RADIO_IGNOR_INPUT2          1083
#define IDC_RADIO_RDR_WT_HOUR           1083
#define IDC_RADIO_REPORT_INPUT2         1084
#define IDC_BUTTON_CONFIG_NEW_READER    1084
#define IDC_RADIO_NO_CHANGE_INPUT2      1085
#define IDC_BUTTON_GET_READER_CONFIG    1085
#define IDC_BUTTON_GET_TAG_LED_CONFIG   1086
#define IDC_RADIO_ENABLE_RELAY          1086
#define IDC_CHECK1                      1087
#define IDC_CHECK_SUPERVISED            1087
#define IDC_CHECK_RDR_FS_LONG           1087
#define IDC_CHECK_ANYID                 1087
#define IDC_CHECK_MODIFY_ID             1087
#define IDC_CHECK_WARP_AROUND           1087
#define IDC_STATIC_RECV                 1088
#define IDC_BUTTON_SET_TAG_LED_CONFIG   1088
#define IDC_CHECK_ASSIGN_READER         1088
#define IDC_RADIO_DISABLE_RELAY         1088
#define IDC_STATIC_SND                  1089
#define IDC_EDIT_TAG_LED                1089
#define IDC_RADIO_RDR_WT_SECOND         1089
#define IDC_CHECK_ANYID_CALL            1089
#define IDC_RADIO_RDR_FS_ABS            1090
#define IDC_EDIT_RDR_FS                 1091
#define IDC_RADIO_RDR_FS_INC            1092
#define IDC_RADIO_RDR_FS_DEC            1093
#define IDC_RADIO_RDR_FS_RANGE          1094
#define IDC_RADIO_RDR_WT_MINUTE         1094
#define IDC_STATIC_SND2                 1095
#define IDC_RADIO_RDR_WT_HR             1095
#define IDC_CHECK_SFGEN_BCAST           1096
#define IDC_BUTTON_CONFIG_NEW_RDR       1096
#define IDC_RADIO_RESP_ANY_RDR          1097
#define IDC_RADIO_RESP_SPECIFIC_RDR     1098
#define IDC_CHECK_QUERY_SFGEN_BCAST     1099
#define IDC_EDIT1                       1099
#define IDC_EDIT_NEW_TAG_ID             1099
#define IDC_EDIT_IP                     1099
#define IDC_CHECK_SFGEN_CALLTAG_BCAST   1100
#define IDC_EDIT2                       1100
#define IDC_BUTTON_INC_FS_SFGEN         1101
#define IDC_RADIO_SEC                   1101
#define IDC_EDIT_MEM_START_ADDR_WRITE   1101
#define IDC_BUTTON_DEC_FS_SFGEN         1102
#define IDC_RADIO_MIN                   1102
#define IDC_EDIT_MEM_DATA_LEN_WRITE     1102
#define IDC_BUTTON_ABS_FS_SFGEN         1103
#define IDC_RADIO_HOUR                  1103
#define IDC_CHECK_SFGEN_SETFS_BCAST     1104
#define IDC_RADIO_ACCESS                1104
#define IDC_CHECK_SFGEN_CALLTAG_BCAST2  1105
#define IDC_RADIO_ASSET                 1105
#define IDC_RADIO_INVENTORY             1106
#define IDC_CHECK_RDR_MD_HIGH           1106
#define IDC_RADIO_ACCESS_TAG            1106
#define IDC_RADIO_ANYTYPE               1107
#define IDC_CHECK_RDR_MD_ENABLE         1107
#define IDC_RADIO_ASSET_TAG             1107
#define IDC_RADIO_ANY_TYPE              1107
#define IDC_CHECK_RDR_RESP_BCAST        1108
#define IDC_EDIT_HOST                   1108
#define IDC_RADIO_INVENTORY_TAG         1108
#define IDC_EDIT6                       1109
#define IDC_CHECK_RDR_ENABLE_PWUP       1109
#define IDC_RADIO_ANYTYPE_TAG           1109
#define IDC_EDIT_NEW_RESEND_TIME        1109
#define IDC_RADIO_LONG_INT              1110
#define IDC_CHECK_RDR_SEND_RSSI         1110
#define IDC_RADIO_SHORT_INT             1111
#define IDC_CHECK_TAG_LED               1111
#define IDC_RADIO_MD_ENABLE             1112
#define IDC_CHECK_RDR_CFG_RDR_ID        1112
#define IDC_EDIT_SFGEN_HOST             1112
#define IDC_RADIO_MD_DISABLE            1113
#define IDC_CHECK_RDR_CFG_HOST_ID       1113
#define IDC_RADIO_MD_ACTIVE_HIGH        1114
#define IDC_CHECK_RDR_CFG_RDR_ID2       1114
#define IDC_CHECK_RDR_CFG_RDR_OPTIONS   1114
#define IDC_RADIO_MD_ACTIVE_LOW         1115
#define IDC_CHECK_TAG_SPEAKER           1115
#define IDC_STATIC_READER_ID            1116
#define IDC_CHECK_RDR_CFG_TYPE          1116
#define IDC_STATIC_HOST_ID              1117
#define IDC_CHECK_RDR_CFG_TX            1117
#define IDC_CHECK_RDR_CFG_TX_TIME       1117
#define IDC_STATIC_SFGEN_ID             1118
#define IDC_CHECK_RDR_CFG_TX2           1118
#define ID_BUTTON_SET                   1119
#define IDC_EDIT_TAG_SPEAKER            1119
#define IDC_STATIC_MSG                  1120
#define IDC_BUTTON_GET_TAG_SPEAKER_CONFIG 1120
#define IDC_EDIT_FS                     1120
#define TX_IDC_LIST                     1121
#define IDC_BUTTON_SET_TAG_TEMP_CALIB3  1121
#define IDC_BUTTON_SET_TAG_SPEAKER_CONFIG 1121
#define IDC_RADIO_SHORT_RND             1121
#define RX_IDC_LIST                     1122
#define IDC_BUTTON_CONFIG_INPUT_PORT    1122
#define IDC_RADIO_LONG_RND              1122
#define IDC_BUTTON_RX_CLEAR             1123
#define IDC_BUTTON_QUERY_FGEN           1123
#define IDC_BUTTON_START_DEBUG          1124
#define IDC_BUTTON_TX_CLEAR             1124
#define IDC_BUTTON_STOP_DEBUG           1125
#define IDC_BUTTON_RX_STOP              1125
#define IDC_STATIC_FS                   1125
#define IDC_BUTTON_RX_STOP2             1126
#define IDC_BUTTON_TX_STOP              1126
#define IDC_BUTTON_CONFIG_FGEN          1126
#define IDC_BUTTON_DEBUG_CLOSE          1127
#define IDC_TAB_API                     1130
#define IDC_RADIO_ACCESS_CALL           1130
#define IDC_RADIO_ASSET_CALL            1131
#define IDC_RADIO_INVENTORY_CALL        1132
#define IDC_RADIO_ANYTYPE_CALL          1133
#define IDC_RADIO_9600                  1133
#define IDC_RADIO_ENABLE_RDR            1141
#define IDC_RADIO_DISABLE_RDR           1142
#define IDC_RADIO_RDR_RANGE_LONG        1143
#define IDC_RADIO_RDR_RANGE_SHORT       1144
#define IDC_RADIO_NEW_CONFIG            1145
#define IDC_RADIO_RELAY                 1146
#define IDC_RADIO_INPUT                 1148
#define IDC_RADIO_FS                    1149
#define IDC_RADIO_ENABLE_DISABLE        1150
#define IDC_STATIC_00                   1152
#define IDC_STATIC_01                   1153
#define IDC_STATIC_02                   1154
#define IDC_STATIC_03                   1155
#define IDC_STATIC_04                   1156
#define IDC_STATIC_3                    1156
#define IDC_STATIC_GROUP_RDR_OPTION     1157
#define IDC_GROUP_NEW_RDR_CONFIG        1158
#define IDC_GROUP_TX_FGEN               1159
#define IDC_STATIC_1                    1160
#define IDC_STATIC_2                    1161
#define IDC_CHECK_RDR_CFG_FGEN          1162
#define IDC_CHECK_RDR_WT_TIME           1162
#define IDC_CHECK_RDR_CFG_WT_TIME       1162
#define IDC_STATIC_05                   1163
#define IDC_GROUP_INPUT1                1164
#define IDC_GROUP_INPUT2                1165
#define IDC_GROUP_INPUT                 1166
#define IDC_GROUP_FS                    1167
#define IDC_GROUP_VALUE                 1168
#define IDC_GROUP_RANGE                 1169
#define IDC_GROUP_RELAY                 1170
#define IDC_GROUP_RELAY_ADDR            1171
#define IDC_GROUP_RELAY_ENABLE          1172
#define IDC_GROUP_ENABLE_RDR            1173
#define IDC_STATIC_GROUP_RDR_TYPE       1174
#define IDC_RADIO_FACTORY               1177
#define IDC_RADIO_TEMP                  1178
#define IDC_RADIO_TEMP_CALIB            1179
#define IDC_RADIO_LED_CONFIG            1180
#define IDC_RADIO_SPEAKER_CONFIG        1181
#define IDC_RADIO_CONFIG                1182
#define IDC_GROUP_TEMP                  1183
#define IDC_GROUP_TEMP_CALIB            1184
#define IDC_GROUP_LED_CONFIG            1185
#define IDC_STATIC_06                   1187
#define IDC_EDIT_FGEN                   1188
#define IDC_RADIO_WRITE_TAG             1188
#define IDC_EDIT_NEW_FGEN               1189
#define IDC_RADIO_READ_TAG              1189
#define IDC_EDIT_READER                 1190
#define IDC_EDIT_TX                     1191
#define IDC_EDIT_WT                     1192
#define IDC_EDIT_TAG                    1193
#define IDC_EDIT_TAG_CALL               1194
#define IDC_EDIT_SFGEN_READER           1195
#define IDC_GROUP_CONFIG                1197
#define IDC_GROUP_QUERY                 1198
#define IDC_GROUP_CALL_TAG              1199
#define IDC_RADIO_QUERY                 1200
#define IDC_RADIO_CALLTAG               1201
#define IDC_STATIC_07                   1202
#define IDC_STATIC_08                   1203
#define IDC_STATIC_09                   1204
#define IDC_STATIC_8                    1205
#define IDC_STATIC_11                   1205
#define IDC_STATIC_31                   1205
#define IDC_GROUP_TAG_TYPE              1206
#define IDC_GROUP_MD_ACTIVE             1207
#define IDC_GROUP_INTERVAL              1208
#define IDC_EDIT_RDR_ID                 1209
#define IDC_GROUP_RS232                 1210
#define IDC_GROUP_NETWORK               1211
#define IDC_GROUP_ENCRPT                1212
#define IDC_GROUP_IPTYPE                1213
#define IDC_GROUP_COMM                  1215
#define IDC_BUTTON1                     1216
#define IDC_BUTTON_CLEAR_MSG_LIST       1216
#define IDC_BUTTON_CONFIG_TAG           1216
#define IDC_BUTTON2                     1217
#define IDC_BUTTON_STOP                 1217
#define IDC_GROUP_INTERVAL_CALL         1218
#define IDC_GROUP_WT                    1222
#define IDC_GROUP_MD_STATUS             1223
#define IDC_RADIO_ENABLE_MD             1224
#define IDC_RADIO_DISABLE_MD            1225
#define IDC_RADIO_SEC_WT                1228
#define IDC_RADIO_MIN_WT                1229
#define IDC_RADIO_HOUR_WT               1230
#define IDC_GROUP_WRITE_TAG             1231
#define IDC_GROUP_READ_TAG              1232
#define IDC_STATIC_10                   1233
#define IDC_STATIC_12                   1234
#define IDC_STATIC_13                   1235
#define IDC_STATIC_14                   1236
#define IDC_STATIC_15                   1237
#define IDC_EDIT_MEM_START_ADDR_READ    1238
#define IDC_EDIT_MEM_DATA_LEN_READ      1239
#define IDC_STATIC_16                   1240
#define IDC_CHECK_RDR_CFG_OPTIONS       1241
#define IDC_EDIT_DEFINE_TAG_READER      1241
#define IDC_IP_LIST                     1242
#define IDC_LIST_IPS                    1243
#define IDC_CHECK_MODIFY_TYPE           1243
#define IDC_CHECK_MODIFY_TIFGC          1244
#define IDC_CHECK_MODIFY_SEND_TIME      1246
#define IDC_CHECK_MODIFY_RPT_TAMPER     1247
#define IDC_COMBO_NEW_TAG_TYPE          1251
#define IDC_RADIO_CFG_SEC               1255
#define IDC_RADIO_CFG_MIN               1256
#define IDC_RADIO_CFG_HOUR              1257
#define IDC_CHECK_MODIFY_FACTORY        1259
#define IDC_CHECK_TAG_TEMP_LOGGING      1259
#define IDC_CHECK_SET_FACTORY           1260
#define IDC_STATIC_CFG_01               1261
#define IDC_STATIC_CFG_02               1262
#define IDC_STATIC_CFG_03               1263
#define IDC_STATIC_CFG_05               1265
#define IDC_GROUP_TAG_CONFIG            1267
#define IDC_RADIO_REPORT_TAMPER         1269
#define IDC_RADIO_CFG_RPT_TAMPER_HISTORY 1270
#define IDC_RADIO_NO_REPORT             1271
#define IDC_GROUP_TAMPER                1272
#define IDC_GROUP_TIFGC                 1273
#define IDC_GROUP_RESEND_TIME           1274
#define IDC_STATIC_CFG_11               1275
#define IDC_STATIC_CFG_17               1276
#define IDC_COMBO_NEW_FIELD_TIME        1277
#define IDC_COMBO_NEW_GROUP_CT          1278
#define IDC_RADIO_DEFINE_TAG_READER     1279
#define IDC_GROUP_DEFINE_TAG_READER     1280
#define IDC_SCROLLBAR1                  1281

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1282
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
